apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 909060519780.dkr.ecr.us-west-2.amazonaws.com/capstone:latest
          ports:
            - containerPort: 5000